# Generated by Django 3.0.6 on 2020-05-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_books_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'permissions': [('special_status', 'Can read all books')], 'verbose_name_plural': 'Books'},
        ),
    ]
